//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amaliat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Amaliat()
        {
            this.NirooYeganVahedAmaliats = new HashSet<NirooYeganVahedAmaliat>();
            this.ShahidAmaliats = new HashSet<ShahidAmaliat>();
            this.NoghteAsars = new HashSet<NoghteAsar>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Ramz { get; set; }
        public Nullable<System.DateTime> TarikheShoroo { get; set; }
        public Nullable<System.DateTime> TarikhePayan { get; set; }
        public string Tozihat { get; set; }
        public string Kholase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NirooYeganVahedAmaliat> NirooYeganVahedAmaliats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShahidAmaliat> ShahidAmaliats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoghteAsar> NoghteAsars { get; set; }
    }
}
