//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ashnayan
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Tozihat { get; set; }
        public string Kholase { get; set; }
        public Nullable<int> IDShahid { get; set; }
        public Nullable<int> IDNoeRabete { get; set; }
    
        public virtual NoeRabete NoeRabete { get; set; }
    }
}
