//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mogheyat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mogheyat()
        {
            this.NoghteAsars = new HashSet<NoghteAsar>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Tozihat { get; set; }
        public Nullable<int> IDMantaghe { get; set; }
    
        public virtual Mantaghe Mantaghe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoghteAsar> NoghteAsars { get; set; }
    }
}
