//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShahidAmaliat
    {
        public int IDAmaliat { get; set; }
        public int IDShahid { get; set; }
        public Nullable<bool> ISMonjarBeShahadat { get; set; }
        public Nullable<int> IDRaste { get; set; }
        public Nullable<int> IDVahed { get; set; }
        public Nullable<int> IDYegan { get; set; }
        public Nullable<int> IDNiroo { get; set; }
    
        public virtual Amaliat Amaliat { get; set; }
        public virtual NirooYeganVahedAmaliat NirooYeganVahedAmaliat { get; set; }
        public virtual Raste Raste { get; set; }
        public virtual Shahid Shahid { get; set; }
    }
}
