//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewNirooVahed
    {
        public string NameNiroo { get; set; }
        public int IDNiroo { get; set; }
        public string NameYegan { get; set; }
        public int IDYegan { get; set; }
        public string NameVahed { get; set; }
        public int IDVahed { get; set; }
    }
}
