//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewShahid
    {
        public int ID { get; set; }
        public string CodeMeli { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public Nullable<System.DateTime> TarikheTavalod { get; set; }
        public Nullable<System.DateTime> TarikheShahadat { get; set; }
        public string NamePedar { get; set; }
        public string Jensiat { get; set; }
        public string Shoghl { get; set; }
        public byte[] QRCode { get; set; }
        public Nullable<int> IDBakhsheTavalod { get; set; }
        public Nullable<System.Guid> AttachID { get; set; }
        public string VaziateShahid { get; set; }
        public string NameBakhash { get; set; }
        public string NameShahrestan { get; set; }
        public string NameOstan { get; set; }
    }
}
